AppBundle\Entity\Tag:
  type: entity
  table: tag
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      unique: true
  manyToMany:
    documents:
      targetEntity: AppBundle\Entity\Document
      mappedBy: tags

